pi-top/pi-top-4-Miniscreen

- src/components/MenuManager.py
Closes #120
Displays ["starfield"](https://github.com/rm-hull/luma.examples/blob/master/examples/starfield.py) on repeat - this was chosen as it relatively evenly distributes the pixels that are switched on.
After unblanking, the display will ignore button presses for 0.6s to prevent accidental interaction with the menu.
Note that this, for some reason, speeds up the frame rate dramatically. It is not yet clear why, but it doesn't seem to be causing any issues, either!
Changes to the underlying menu page once it has dimmed are not currently being handled. For comparison, CPU page will not sleep, but battery page will - and disconnecting the power cable does not cause the screensaver to stop playing. This might be the desired behaviour (nothing happened on screen before sleeping, so now …
> 2 minute screensaver

- pt_miniscreen/app.py
- pt_miniscreen/config/classes/menu.py
- pt_miniscreen/config/classes/menu_app.py
- pt_miniscreen/config/classes/title_bar.py
- pt_miniscreen/config/config.py
- pt_miniscreen/config/manager.py
- pt_miniscreen/event.py
- pt_miniscreen/hotspots/base.py
- pt_miniscreen/hotspots/marquee_text_hotspot.py
- pt_miniscreen/menu.py
- pt_miniscreen/menu_manager.py
- pt_miniscreen/pages/base.py
- pt_miniscreen/pages/hud/battery.py
- pt_miniscreen/pages/hud/wifi.py
- pt_miniscreen/pages/overlay/title_bar.py
- pt_miniscreen/pages/settings/connection.py
- pt_miniscreen/pages/settings_connection/action.py
- pt_miniscreen/state.py
- pt_miniscreen/viewport.py
Handles page size changes due to title bar on parent menu:
- When navigating through menus, the title bar is updated based on the menu's title bar behaviour setting (`TitleBarBehaviour`), specified in `config.py`.
- If the title bar changes it's height in a particular menu, the `TITLE_BAR_HEIGHT_CHANGED` event is emitted.
- When the `TITLE_BAR_HEIGHT_CHANGED` event is emitted, `MenuManager` updates the current menu height. The menu will internally resize it's `viewport`, its `hotspots` and their positions.
Also:
- `MarqueeTextHotspot` reduces its `interval` if no scrolling is needed.
- Added `height` and `width` properties to `PageBase`, `Hotspot` and `Viewport` classes.
- Added `window_height` and `window_width` properties to `MenuBase` class. …
> Handle page size changes due to title bar on parent menu

- pt_miniscreen/app.py
- pt_miniscreen/event.py
- pt_miniscreen/hotspot_manager.py
- pt_miniscreen/hotspots/marquee_text_hotspot.py
- pt_miniscreen/menu.py
- pt_miniscreen/menu_manager.py
- pt_miniscreen/pages/overlay/title_bar.py
- pt_miniscreen/state.py
Support hotspots with different refresh rates. All of the logic that deals with menu/hotspot intervals is now decoupled from `App` into `MenuManager`
Displayed image is updated when:
- The `ACTIVE_HOTSPOT_HAS_NEW_CACHED_IMAGE` event is emitted by a hotspot.
- When skipping/navigating through pages.
Also:
- Adds `active` property to `HotspotManager` to determine when if the hotspot should be updating its image.
- Hotspots don't generate images when it's `HotspotManager` isn't active.
TODO:
- Improve "busy wait" on thread that updates cached images - use events instead instead of sleeping.
> Update displayed image when hotspot is redrawn

- pt_miniscreen/app.py
- pt_miniscreen/hotspots/bootsplash.py
- pt_miniscreen/hotspots/templates/image.py
- pt_miniscreen/hotspots/templates/marquee_dynamic_text.py
- pt_miniscreen/hotspots/templates/marquee_text.py
- pt_miniscreen/hotspots/templates/rectangle.py
- pt_miniscreen/hotspots/templates/status_icon.py
- pt_miniscreen/hotspots/templates/text.py
- pt_miniscreen/pages/hud/battery.py
- pt_miniscreen/pages/hud/cpu.py
- pt_miniscreen/pages/hud/network_page_base.py
- pt_miniscreen/pages/templates/action/page.py
- pt_miniscreen/pages/templates/menu/page.py
- pt_miniscreen/tiles/title_bar/settings.py
Fix imports so application runs:
- Updated imports from files that were moved to different folders.
- Import `imgcat`, used for debug purposes, only when used.
> Fix broken imports

- pt_miniscreen/app.py
I ran into this error on a fresh boot which caused my miniscreen menu to not respond to button presses:
```
-- Boot a55c6108508649229ce2a4ea7c963a84 --
Feb 03 12:35:46 pi-top systemd[1]: Started pi-top OLED system menu.
Feb 03 12:36:08 pi-top pt-miniscreen[1004]: Exception in thread Thread-4:
Feb 03 12:36:08 pi-top pt-miniscreen[1004]: Traceback (most recent call last):
Feb 03 12:36:08 pi-top pt-miniscreen[1004]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Feb 03 12:36:08 pi-top pt-miniscreen[1004]:     self.run()
Feb 03 12:36:08 pi-top pt-miniscreen[1004]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Feb 03 12:36:08 pi-top pt-miniscreen[1004]:     self._target(*self._args, **self._kwargs)
Feb 03 12:36:08 pi-top pt-miniscreen[1004]:   File …
```
> Create app StateManager before calling setup_events which uses it

- pt_miniscreen/app.py
| Ready | - |
- Reverts the change of https://github.com/pi-top/pi-top-4-Miniscreen/pull/207 and handles the issue differently. That change tried to ensure the hard dependency of setup_events on StateManager, but ignored the much greater soft dependency of StateManager's events on the setup_events handlers. As a result that change the pi-top splash animation wasn't shown because it's event was missed, and initial button presses were often not handled either. So now setup_events is first again, and just has a guard clause against handling buttons before StateManager is created.
[insert screenshots here]
-
-
- @olivierwilkinson
> Create StateManager after setup_events, reverts a13f287

- pt_miniscreen/actions.py
Running `wifi-ap-sta stop` isn't enough to clean all the modified configuration files.
> 'stop' & 'disable' AP mode on action page

- pt_miniscreen/app.py
| Ready | - |
I've run into the below error twice today whilst testing the miniscreen control swaps, and it causes the main rendering thread to crash. We should catch this exception in the sdk too probably.
```
Feb 15 17:44:44 pi-top pt-miniscreen[816]: User has taken control of the miniscreen
Feb 15 17:45:21 pi-top pt-miniscreen[816]: User has given back control of the miniscreen
Feb 15 17:45:21 pi-top pt-miniscreen[816]: Forcing full state refresh...
Feb 15 17:45:21 pi-top pt-miniscreen[816]: Exception in thread Thread-21:
Feb 15 17:45:21 pi-top pt-miniscreen[816]: Traceback (most recent call last):
Feb 15 17:45:21 pi-top pt-miniscreen[816]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Feb 15 17:45:21 pi-top …
```
> Try except miniscreen reset

- pt_miniscreen/generators/scroll.py
- pt_miniscreen/hotspots/scrollbar.py
- pt_miniscreen/pages/hud/overview.py
- pt_miniscreen/pages/system/battery.py
- pt_miniscreen/pages/system/cpu.py
- pt_miniscreen/pages/templates/menu/page.py
- pt_miniscreen/tiles/menu/hud.py
- pt_miniscreen/tiles/menu/network.py
- pt_miniscreen/tiles/menu/settings.py
- pt_miniscreen/tiles/menu/system.py
- pt_miniscreen/tiles/templates/paginated.py
| Ready | [OS-1209](https://pi-top.atlassian.net/browse/OS-1209) |
Add scrollbar hotspot to PaginatedTile. While PaginatedTile is
inheriting from ViewportTile it is not possible to add a hotspot that
scrolls independently of the pages, inherit from Tile instead. In order
for PaginatedTile to render the scrollbar hotspot as well as the
ViewportTile the `get_preprocess_image` method needs to be overridden.
This is so the initial image can have the pages ViewportTile's image
pasted in.
Override the PaginatedTile's `__setattr__` method in order to keep the
`active` state of the pages ViewportTile in sync.
Pass Page classes instead of instances to PaginatedTile so they can be
instantiated with the correct size. The size must now take the scrollbar …
> feat: add scrollbar to PaginatedTile

- pt_miniscreen/hotspots/templates/marquee_dynamic_text.py
- pt_miniscreen/pages/hud/overview.py
| Ready | [OS-1212](https://pi-top.atlassian.net/browse/OS-1212]) |
Add IP to overview page
Move the overview page's battery indicator and charge percentage text up
and add the antenna icon and the user's IP below it. The IP is chosen by
iterating over the Wi-Fi, ethernet, usb and localhost interfaces and
using the first one that is valid.
Use the dynamic marquee text hotspot for the IP so that it is updated
periodically and handles long IPs elegantly.
Fix two memory leaks in the dynamic marquee text hotspot:
- the update thread is never stopped and has a reference to self
- if the hotspot is never active the loop hangs waiting to become active
forever
For the first memory leak add a stop event and set it when the cleanup
method is called. For …
> feat: add IP to overview page

- pt_miniscreen/app.py
- pt_miniscreen/pages/templates/action/page.py
When there's an error while running the action in an action page, the app would crashes but not restart since it doesn't exit with errors; `getattr` can't read/get name-mangled variables (the ones that start with `__`) so the error isn't propagated all the way to the top.
Also - use the action page & status icon `UNKNOWN` state, which draws a question mark in the status-circle when something goes wrong.
> Improve action page error handling

- pt_miniscreen/pages/network/network_page_base.py
- pt_miniscreen/pages/templates/action/page.py
- pt_miniscreen/tile_groups/hud.py
When adding a title to the network pages I noticed that the size was incorrect for the pages. This PR fixes that issue separately from a feature.
When adding the right gutter to the HUDTileGroup the size of child tiles
should have been reduced by the width of the gutter.
The gutter was manually accounted for in the child tiles and so this
does not change any user facing layout.
In the base network page the right margin had 10 extra pixels on it.
In the base action page the wrong column was actually passed to the
text, fixing this error actually caused the layout to be unchanged.
> refactor: fix HUD giving children the wrong size

- pt_miniscreen/hotspots/templates/text.py
- pt_miniscreen/pages/hud/overview.py
- pt_miniscreen/pages/system/battery.py
- pt_miniscreen/pages/templates/action/page.py
- pt_miniscreen/pages/templates/menu/page.py
Align text horizonally to boundaries when `align` is set. Options match
Pillow's `align` options: "left", "right" and "center" where "left" is
the default.
Add `vertical_align` property that aligns text similarly to `align` but
with vertical boundaries. Options are "top", "bottom" and "center" where
"top" is the default.
Set `vertical_align` to "center" in the base action page. Since the
previous default was to center the text horizontally and vertically the
action page text needs to be manually set to "center"
Remove `xy` and `anchor` properties since they are now superceded by the
align properties. Anchor is always left-top "lt" so that text xy
position can be calculated based off align values, text size and hotspot
size.
Incorperate MiniscreenAssistant logic into the TextHotspot. This …
> feat: add boundary alignment to text hotspot

- pt_miniscreen/pages/hud/overview.py
- tests/mocks/sys_info.py
- tests/overview_test.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/<ticket-number>) |
- Update how device IP is retrieved, using a new helper in the SDK https://github.com/pi-top/pi-top-Python-SDK/pull/521
N/A
-
- Install artifacts
- Install https://github.com/pi-top/pi-top-Python-SDK/pull/521 artifacts
- Restart miniscreen app `sudo systemctl restart pt-miniscreen`
-
> Get device IP using SDK

- pt_miniscreen/core/components/marquee_text.py
multiprocessing.Event was used by accident
> fix: use threading.Event in marquee text

- conftest.py
- pt_miniscreen/core/app.py
- pt_miniscreen/core/component.py
- pt_miniscreen/core/components/image.py
- pt_miniscreen/core/components/list.py
- pt_miniscreen/core/components/marquee_text.py
- tests/core_app_test.py
- tests/core_component_test.py
- tests/core_image_component_test.py
- tests/core_list_component_test.py
- tests/core_marquee_text_component_test.py
- tests/core_smoke_test.py
| Ready | [None](https://pi-top.atlassian.net/browse/<ticket-number>) |
- pause components when not rendered
Intervals running in the background that do not change what is being
displayed on the screen cause performance to drop as an application
scales.
Pause components when they are not being rendered. Pausing a component
means that it's intervals will wait until the component becomes active
again to continue. We know that a component can be paused when it is not
being rendered, since it will never change the output of it's parent.
To track whether a component is being rendered we need to know if it's
render method is called by it's parent's render method. To do this we
can have components mark themselves as rendered whenever their render …
> Component pausing

- debian/control
- pt_miniscreen/actions.py
- tests/mocks/sys_info.py
- tests/settings_test.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1332) |
- VNC toggle in the Settings Page also controls the `pt-web-vnc-desktop` systemd service.
[insert screenshots here]
-
-
-
> Control pt-web-vnc-desktop in VNC action page

- pt_miniscreen/app.py
| Ready | no Ticket |
This was prompted by the following error, which I've seen before. It can be triggered if you press a button before the app is started. app.root is not created until the start method is called but the interactions created in init are expecting it to exist.
```
Aug 15 12:24:00 pi-top systemd[1]: Starting pi-top OLED system menu...
Aug 15 12:24:03 pi-top systemd[1]: Started pi-top OLED system menu.
Aug 15 12:24:07 pi-top pt-miniscreen[9813]: Exception in thread Thread-6:
Aug 15 12:24:07 pi-top pt-miniscreen[9813]: Traceback (most recent call last):
Aug 15 12:24:07 pi-top pt-miniscreen[9813]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Aug 15 12:24:07 pi-top pt-miniscreen[9813]:     self.run()
Aug 15 …
```
> Fix button handler crash

- .github/workflows/deb-build.yml
- .github/workflows/deb-release.yml
- pt_miniscreen/__init__.py
- pt_miniscreen/version.py
- setup.cfg
- setup.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/<ticket-number>) |
Set package version on build-time using the `PYTHON_PACKAGE_VERSION` environment variable:
- Update workflows to provide this variable when building the package. In these workflows, the version is generated to either provide a snapshot changelog (on PR builds) or read from the actual changelog file (on release builds).
- The python module now provides `__version__`. It reports the package version using `pkg_resources.get_distribution`. This assumes the package is installed in the system. 
[insert screenshots here]
-
-
-
> Set package version using environment variable

- pt_miniscreen/root.py
When scrolling through the Root pages the first frame of the gifs don't wait for the full duration before changing, giving the appearance that they are sped up initially.
This is due to the default behaviour of the core List component: it uses a snapshot of the scrolling rows to improve performance for complex rows, this snapshot remains on the first frame longer than the gif does, giving the illusion of it being sped up once scrolling finishes.
Turn off this behaviour of the List by setting
`use_snapshot_when_scrolling` to `False` so that the gif animates while scrolling, keeping frame time consistent.
> fix: sped up menu gif after scroll

- pt_miniscreen/core/component.py
- tests/core_component_test.py
Assigning to Component.state breaks the internal representation of a component and prevents it from notifying the parent of a change.
Raise a helpful error when a user tries to assign to `state`.
> fix: prevent assigning to Component.state

- pt_miniscreen/pages/root/bluetooth_pairing.py
Dashboard won't display the Bluetooth pairing option if further-link isn't installed, however, when importing/loading/using the miniscreen module/app, the further-link import causes it to crash if not available.
> Don't fail if further-link isn't installed

- pt_miniscreen/pages/system/last_update.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/<ticket-number>) |
- pi-topOS lite support: don't fail when pt-firmware-updater isn't installed.
[insert screenshots here]
-
-
-
> Don't fail if firmware updater isn't installed

- .github/workflows/deb-build.yml
- pt_miniscreen/core/components/stack.py
- pt_miniscreen/pages/root/projects/utils.py
- tests/README.md
- tests/projects_test.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/SWE-335), [Ticket](https://pi-top.atlassian.net/browse/SWE-336) |
Issue # 1: When deleting a project on bookworm OS, the app crashes.
Fix: Newer versions of PIL have a crop method that will raise an error if the crop boundaries are invalid. Previously, it didn't perform any checks.
Issue # 2: Sometimes projects in the user folders wouldn't be displayed in the menu.
Fix: This happens because the variable for user home directory was generated when the app started. If the systemd service that runs the app starts when there's no display available yet (which is what we use to determine the username and its home folder), this variable would be set to empty, which is why the projects are not …
> Fix project page issues
